version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python --version
      - pip install --upgrade pip
      - |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found"
        fi

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - echo "Running lint/tests if available"
      - echo 'This is my first build on aws'
      - |
        if [ -f pytest.ini ] || [ -d tests ]; then
          pytest || echo "Tests failed but continuing"
        else
          echo "No tests found"
        fi

  build:
    commands:
      - echo "Build phase started"
      - echo "Nothing to compile for Python app"

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
